### ISSUE TITLE
Possible bug in setup when sampling is 'full'

### ISSUE THREAD

**Issue by jstutters** [NYU-DiffusionMRI/dwidenoise#2]
Hi,

I've been reading through MPdenoising.m trying to understand it.  Should this line:

https://github.com/NYU-DiffusionMRI/mppca_denoise/blob/171734436a1c565d243e7715d25f5c8b97fba5ae/MPdenoising.m#L126

Actually be: `mask(:,:,sz-k(3):sz) = 0;`  Otherwise it seems inconsistent with the previous 5 lines for x and y axes.

**Comment by badesar1** [comment]
Thanks for reporting this. The problem has been resolved
